spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_board
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  level:
    com.parser: DEBUG
  file:
    name: application.log
